global using Microsoft.Xna.Framework;
global using Terraria;
global using Terraria.ID;
global using Terraria.ModLoader;
global using Terraria.DataStructures;
global using MightofUniverses.Common;
global using MightofUniverses.Common.Players;
global using MightofUniverses.Common.Abstractions;
global using MightofUniverses.Common.Util;